version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/whitneychampion.com
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: remove .git and .circleci
          command: rm -rf whitneychampion.com/.git && rm -rf whitneychampion.com/.gitignore && rm -rf whitneychampion.com/.circleci
      - run:
          name: deploy to S3
          branch: master
          command: aws s3 sync . s3://whitneychampion.com/ --region us-east-1
      - run:
          name: invalidate cloudfront
          command: aws cloudfront create-invalidation --distribution-id E8CHANVCT72GZ --paths /index.html /style.css /Resume.pdf

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
