version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/whitneychampion.com
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: remove .git and .circleci
          branch: master
          command: rm -rf .git && rm -rf .gitignore && rm -rf .circleci
      - run:
          name: deploy to S3
          branch: master
          command: aws s3 sync . s3://whitneychampion.com/ --region us-east-1 --acl public-read
      - run:
          name: deploy to S3
          branch: master
          command: cd art; aws s3 sync . s3://angry.unicorns.lol/ --region us-east-1 --acl public-read
      - run:
          name: invalidate cloudfront
          branch: master
          command: aws cloudfront create-invalidation --distribution-id E8CHANVCT72GZ --paths / /index.html /style.css /Resume.pdf
      - run:
          name: invalidate cloudfront
          branch: master
          command: aws cloudfront create-invalidation --distribution-id E3N3ZQUHQY310Z --paths / /index.html /css/style.css

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
