dependencies:
    override:
        - sudo pip install awscli

deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/whitneychampion.com s3://whitneychampion.com --region us-east-1 --delete

