version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: 
	  command: |
	    - aws s3 sync whitneychampion.com s3://whitneychampion.com/ --delete
